metric_bev: true
image_points:
  - [190.0, 160.0]
  - [450.0, 160.0]
  - [585.0, 350.0]
  - [55.0, 350.0]
world_points:
  - [-3.0, 8.0]
  - [3.0, 8.0]
  - [3.0, 0.0]
  - [-3.0, 0.0]
homography:
  - [0.0231, -0.0164, -0.992]
  - [0.0, -0.0518, 8.282]
  - [0.0, -0.00546, 1.0]
bev:
  width_px: 600
  height_px: 800
  x_min_m: -3.0
  x_max_m: 3.0
  y_min_m: 0.0
  y_max_m: 8.0
  resolution_m_per_pixel: 0.01

